name: Update vk-hdr-layer

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-vk-hdr-layer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get Latest Commit
        id: get-commit
        continue-on-error: true
        run: |
          max_retries=5
          attempt=0
          success=false

          while [ $attempt -lt $max_retries ]; do
            echo "Attempt $((attempt+1)) to fetch commit..."
            response=$(curl -s --fail https://api.github.com/repos/Zamundaaa/VK_hdr_layer/commits/master) && success=true && break
            attempt=$((attempt+1))
            sleep 5
          done

          if [ "$success" = true ]; then
            latest_commit=$(echo "$response" | jq -r '.sha')
            git_date=$(echo "$response" | jq -r '.commit.committer.date' | sed 's/[-:]//g')

            echo "latest-commit=$latest_commit" >> $GITHUB_OUTPUT
            echo "git-date=$git_date" >> $GITHUB_OUTPUT
            echo "latest-tag=$latest_tag" >> $GITHUB_OUTPUT
          else
            echo "Failed to fetch commit after $max_retries attempts."
            echo "latest-commit=" >> $GITHUB_OUTPUT
            echo "git-date=" >> $GITHUB_OUTPUT
            echo "latest-tag=" >> $GITHUB_OUTPUT
          fi

      - name: Get current date
        id: get-current-date
        run: |
          echo "current_date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Get current commit in spec
        id: get-current-commit
        run: |
          current_commit=$(grep -oP '(?<=^%global longcommit ).*' vk-hdr-layer.spec || echo "")
          current_commit=$(echo "$current_commit" | tr -d '[:space:]')
          echo "current_commit=$current_commit" >> $GITHUB_OUTPUT

      - name: Compare Commits
        id: compare-commits
        run: |
          latest="${{ steps.get-commit.outputs.latest-commit }}"
          current="${{ steps.get-current-commit.outputs.current-commit }}"

          if [ -z "$latest" ]; then
            echo "No latest commit fetched. Skipping update."
            echo "new-commit=false" >> $GITHUB_OUTPUT
          elif [ "$latest" != "$current" ]; then
            echo "New commit found: $latest"
            echo "new-commit=true" >> $GITHUB_OUTPUT
          else
            echo "No update required."
            echo "new-commit=false" >> $GITHUB_OUTPUT
          fi

      - name: Update Spec File
        if: ${{ contains(steps.compare-commits.outputs.new-commit, 'true') }}
        run: |
          sed -i "s/^%global date .*/%global date ${{ steps.get-current-date.outputs.current_date }}/" vk-hdr-layer.spec
          sed -i "s/^%global commit .*/%global commit ${{ steps.get-latest-commit.outputs.short_commit }}/" vk-hdr-layer.spec
          sed -i "s/^%global longcommit .*/%global longcommit ${{ steps.get-latest-commit.outputs.latest_commit }}/" vk-hdr-layer.spec
          
      - name: Commit and Push Changes
        if: ${{ contains(steps.compare-commits.outputs.new-commit, 'true') }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add vk-hdr-layer.spec
          git commit -m "vk-hdr-layer.spec: Update commit, longcommit, and date macros"
          git push
